# ----------------
# MONITOR
# ----------------

monitor = DP-4, 1920x1080@239.96, 0x0, 1
# ----------------
# VARIABLES
# ----------------
misc {
    vrr = 2
}
$terminal = alacritty
$menu = wofi --show drun

# ----------------
# AUTOSTART
# ----------------
exec-once = ~/.config/waybar/scripts/dynamic_pad.sh
exec-once = waybar
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = hyprpaper
exec-once = hyprlock
exec-once = hypridle
exec-once = mako
WLR_RENDERER=vulkan gamescope -f -- %command%
__GL_THREADED_OPTIMIZATIONS=1 %command%
# ----------------
# ENVIRONMENT
# ----------------

env = XCURSOR_THEME,Bibata-Modern-Classic
env = XCURSOR_SIZE,24

env = HYPRCURSOR_THEME,Bibata-Modern-Classic
env = HYPRCURSOR_SIZE,24
#env = LIBVA_DRIVER_NAME,nvidia
#env = __GLX_VENDOR_LIBRARY_NAME,nvidia
#env = NVD_BACKEND,direct
#env = GL_MAX_GL_FLUSH_HANDLER_TIME,0

# ----------------
# LOOK AND FEEL
# ----------------

general {
    gaps_in = 3
    gaps_out = 8
    border_size = 2

    col.active_border = rgba(aea2e6aa)
    col.inactive_border = rgba(595959aa)
 resize_on_border = true
    extend_border_grab_area = 15
    resize_on_border = true
    allow_tearing = false

    layout = dwindle
}


cursor {
  no_warps = true
    no_hardware_cursors = true
}
dwindle {
    preserve_split = true
    force_split = 2
}
decoration {
    rounding = 8

    blur {
        enabled = true
        size = 3
        passes = 3
        new_optimizations = true
        ignore_opacity = true # Forces blur even if window is semi-transparent
        brightness = 0.9   # < 1.0 = darker blur
        contrast = 1.7     # optional fine-tune
        noise = 0.03       # optional texture
        # xray = true
    }
shadow {
        enabled = true
        range = 20
        render_power = 3
    }
    active_opacity = 0.85
    inactive_opacity = 0.85
    fullscreen_opacity = 1.0
}

animations {
    enabled = true

    bezier = easeOutQuint,0.23,1,0.32,1

    animation = windows,1,5,easeOutQuint
    animation = border,1,10,default
    animation = fade,1,5,default
    animation = workspaces,1,4,default
}

input {
    kb_layout = pt

    follow_mouse = 0


    accel_profile = flat
    touchpad {
        natural_scroll = true
    }

    sensitivity = 0
}

# ----------------
# KEYBINDS
# ----------------

$mainMod = SUPER

bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, Q, killactive
bind = $mainMod, M, exec,hyprlock
bind = $mainMod, E, exec, $menu
bind = $mainMod, F, fullscreen

bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, L, movewindow, r
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, J, movewindow, d

bindel = $mainMod ALT, H, moveactive, -8 0
bindel = $mainMod ALT, L, moveactive, 8 0
bindel = $mainMod ALT, K, moveactive, 0 -8
bindel = $mainMod ALT, J, moveactive, 0 8

bind = $mainMod, T, togglefloating
bind = $mainMod CTRL, H, resizeactive, -50 0
bind = $mainMod CTRL, L, resizeactive, 50 0
bind = $mainMod CTRL, K, resizeactive, 0 -50
bind = $mainMod CTRL, J, resizeactive, 0 50
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = SUPER, F, fullscreen
bind = $mainMod, plus, layoutmsg, mfact +0.05
bind = $mainMod, minus, layoutmsg, mfact -0.05
bind = , 172, exec, playerctl play-pause
bind = , mouse:276, exec, playerctl play-pause

bind = , PRINT, exec, hyprshot -z -m region  --clipboard-only
bindm = SUPER, mouse:272, movewindow
